#!/bin/bash
# Setup the env variable to help manual testing, use "source ./env" to get this work
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!IMPORTANT!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# !!!!!!!!!!!REMEMBER TO RERUN IT AFTER MODIFY BEFORE MANUALLY RUN ANY TESTS!!!!!!

export LOGLVL=5
export HGPORT=9990
export HGHOST=gdos-yanan

export MAIN=$PWD
export THOME=$MAIN/tests
export SRCHOME=$MAIN/server/
export PROCLOG=$MAIN/runtest.proc.log
export SERVERLOG=$MAIN/runtest.server.log
export SERVERHOME=$THOME/.live/
export APPSHOME=$SERVERHOME/apps/

export PATH=$PATH:$MAIN/tests/main
export PATH=$PATH:$MAIN/tests/pre
export PATH=$PATH:$MAIN/tests/act
export PATH=$PATH:$MAIN/tests/post
export PATH=$PATH:$MAIN/tests/printer
export PATH=$PATH:$MAIN/tests/analyzer
export PATH=$PATH:$MAIN/tests/.live
export PATH=$PATH:$MAIN/tests/util
export PATH=$PATH:$MAIN/tests/
