#!/bin/bash

# make and copy the higine server to the live space, with
# its config files

if [ ! -s "$SERVERHOME/higine" ]; then
	opath=$PWD
	# strange because the lib is out of main directory
	cp -rf $SRCHOME/* $SERVERHOME
	cd $SERVERHOME
	make clean >&2
	make >&2
	cd $opath
fi
