#!/bin/bash - 
#===============================================================================
#
#          FILE: app_options_not_recognized_return_error_with_server_available
# 
#         USAGE: ./app_options_not_recognized_return_error_with_server_available 
# 
#   DESCRIPTION: A client submit a job, with a bunch of app options. 
#   			 The server find one of the options not exisited in the program's metadata
#				 Then the job should be terminated and return error message, while the 
#				 server shouldn't die
# 		 INPUTS: 1:the program submitted first; 2:the process number the first program used;
# 		 		 3:the unrecognized option; 4:the program submitted after, to verify the living of server 
#				 5:the process number this program used
#       OPTIONS: ---
#  REQUIREMENTS: ---
#          BUGS: ---
#         NOTES: ---
#        AUTHOR: YANG Anran (), 08to09@gmail.com
#  ORGANIZATION: 
#       CREATED: 03/31/2012 05:19:26 PM CST
#      REVISION:  ---
#===============================================================================

set -o nounset                              # Treat unset variables as an error

invalidopt=$3
APP_OPTIONS_NOT_RECOGNIZED_MESSAGE="start job error, app option $invalidopt not recognized"
_prepare_server
_start_server | _contains $APP_OPTIONS_NOT_RECOGNIZED_MESSAGE | _at server &
sleep 0.1
execute_program $1 $2 $invalidopt | _contains $APP_OPTIONS_NOT_RECOGNIZED_MESSAGE | _at client 
_prepare_program $4; execute_program $4 $5 | _contains_$4_output $5 | _at state
_kill_server
_collect client server state

