#!/bin/bash

PROGRAM_NOT_EXIST_MESSAGE="start job error, program not_exist not exist"
_prepare_server
_start_server | _contains $PROGRAM_NOT_EXIST_MESSAGE | _at server &
sleep 0.1
rm -f $APPSHOME/not_exist $THOME/trash/not_exist$(date +%s) ; execute_program not_exist 2 | _contains $PROGRAM_NOT_EXIST_MESSAGE  | _at client 
_prepare_program $1; execute_program $1 $2 | _contains_$1_output $2 | _at state
_kill_server
_collect client server state
