#!/bin/bash - 
#===============================================================================
#
#          FILE: happy_multijob_flow
# 
#         USAGE: ./happy_multijob_flow 
# 
#   DESCRIPTION: Jobflow which contains multi jobs with precedence between them
#                work well 
#
#		 INPUTS: 1:program 1
#		         2:np for 1
#		         3:program 2
#		         4:np for 2
#		         5:exchange file prefix, MUST in a shared location
#		         6:expected output
#       OPTIONS: ---
#  REQUIREMENTS: ---
#          BUGS: ---
#         NOTES: ---
#        AUTHOR: YANG Anran (), 08to09@gmail.com
#  ORGANIZATION: 
#       CREATED: 04/17/2012 08:42:53 AM CST
#      REVISION:  ---
#===============================================================================

set -o nounset                              # Treat unset variables as an error

_prepare_server
_start_server | _contains $6 | _at server &
_prepare_program $1 ; _prepare_program $3
create_empty_flow.rb | add_job.rb $1 $2 output:$5.exc | add_job.rb $3 $4 input:$5.exc | add_job.rb $3 $4 input:$5.exc | add_order.rb 0 1 | add_order.rb 1 2 | session.rb start.rb block_till_result.rb | _contains $6 | _at client 
_kill_server
_collect server client
rm -f $5.exc
