#!/bin/bash

# test for happy path , or the most "standard" way to use higine, when dealing with single job
# parameters:
# 1:the name of the to-run server-side program
# 2:the process taken to run mpiexec
# (implicit)3:a script called _contains_<program name>_output
# The last param exists because to know a MPI program's exact output is impossible

_prepare_server
_start_server | _contains_$1_output $2 | _at server &
_prepare_program $1 ; echo | add_job.rb $1 $2 | session.rb start_job.rb block_till_result.rb | _contains_$1_output $2 | _at client 
_kill_server
_collect server client
