#!/bin/bash

JOB_NOT_EXIST_MESSAGE="get status error, job flow id not exist"
_prepare_server
_start_server | _contains "$JOB_NOT_EXIST_MESSAGE" | _at server &
sleep 0.1
session.rb block_till_result.rb | _contains "$JOB_NOT_EXIST_MESSAGE" | _at client
_prepare_program $1; execute_program $1 $2 | _contains_$1_output $2 | _at state
_kill_server
_collect client server state
