#
# Autogenerated by Thrift
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'
require 'hpgcjob_types'

module HpgcJob
  class Client
    include ::Thrift::Client

    def start_single_job(job)
      send_start_single_job(job)
      return recv_start_single_job()
    end

    def send_start_single_job(job)
      send_message('start_single_job', Start_single_job_args, :job => job)
    end

    def recv_start_single_job()
      result = receive_message(Start_single_job_result)
      return result.success unless result.success.nil?
      raise result.e unless result.e.nil?
      raise ::Thrift::ApplicationException.new(::Thrift::ApplicationException::MISSING_RESULT, 'start_single_job failed: unknown result')
    end

    def start(flow)
      send_start(flow)
      return recv_start()
    end

    def send_start(flow)
      send_message('start', Start_args, :flow => flow)
    end

    def recv_start()
      result = receive_message(Start_result)
      return result.success unless result.success.nil?
      raise result.e unless result.e.nil?
      raise ::Thrift::ApplicationException.new(::Thrift::ApplicationException::MISSING_RESULT, 'start failed: unknown result')
    end

    def pause(client_ticket)
      send_pause(client_ticket)
      recv_pause()
    end

    def send_pause(client_ticket)
      send_message('pause', Pause_args, :client_ticket => client_ticket)
    end

    def recv_pause()
      result = receive_message(Pause_result)
      return
    end

    def resume(client_ticket)
      send_resume(client_ticket)
      recv_resume()
    end

    def send_resume(client_ticket)
      send_message('resume', Resume_args, :client_ticket => client_ticket)
    end

    def recv_resume()
      result = receive_message(Resume_result)
      return
    end

    def cancel(client_ticket)
      send_cancel(client_ticket)
      recv_cancel()
    end

    def send_cancel(client_ticket)
      send_message('cancel', Cancel_args, :client_ticket => client_ticket)
    end

    def recv_cancel()
      result = receive_message(Cancel_result)
      return
    end

    def get_status(client_ticket)
      send_get_status(client_ticket)
      return recv_get_status()
    end

    def send_get_status(client_ticket)
      send_message('get_status', Get_status_args, :client_ticket => client_ticket)
    end

    def recv_get_status()
      result = receive_message(Get_status_result)
      return result.success unless result.success.nil?
      raise ::Thrift::ApplicationException.new(::Thrift::ApplicationException::MISSING_RESULT, 'get_status failed: unknown result')
    end

  end

  class Processor
    include ::Thrift::Processor

    def process_start_single_job(seqid, iprot, oprot)
      args = read_args(iprot, Start_single_job_args)
      result = Start_single_job_result.new()
      begin
        result.success = @handler.start_single_job(args.job)
      rescue HpgcJobException => e
        result.e = e
      end
      write_result(result, oprot, 'start_single_job', seqid)
    end

    def process_start(seqid, iprot, oprot)
      args = read_args(iprot, Start_args)
      result = Start_result.new()
      begin
        result.success = @handler.start(args.flow)
      rescue HpgcJobException => e
        result.e = e
      end
      write_result(result, oprot, 'start', seqid)
    end

    def process_pause(seqid, iprot, oprot)
      args = read_args(iprot, Pause_args)
      result = Pause_result.new()
      @handler.pause(args.client_ticket)
      write_result(result, oprot, 'pause', seqid)
    end

    def process_resume(seqid, iprot, oprot)
      args = read_args(iprot, Resume_args)
      result = Resume_result.new()
      @handler.resume(args.client_ticket)
      write_result(result, oprot, 'resume', seqid)
    end

    def process_cancel(seqid, iprot, oprot)
      args = read_args(iprot, Cancel_args)
      result = Cancel_result.new()
      @handler.cancel(args.client_ticket)
      write_result(result, oprot, 'cancel', seqid)
    end

    def process_get_status(seqid, iprot, oprot)
      args = read_args(iprot, Get_status_args)
      result = Get_status_result.new()
      result.success = @handler.get_status(args.client_ticket)
      write_result(result, oprot, 'get_status', seqid)
    end

  end

  # HELPER FUNCTIONS AND STRUCTURES

  class Start_single_job_args
    include ::Thrift::Struct, ::Thrift::Struct_Union
    JOB = 1

    FIELDS = {
      JOB => {:type => ::Thrift::Types::STRUCT, :name => 'job', :class => Job}
    }

    def struct_fields; FIELDS; end

    def validate
    end

    ::Thrift::Struct.generate_accessors self
  end

  class Start_single_job_result
    include ::Thrift::Struct, ::Thrift::Struct_Union
    SUCCESS = 0
    E = 1

    FIELDS = {
      SUCCESS => {:type => ::Thrift::Types::I32, :name => 'success'},
      E => {:type => ::Thrift::Types::STRUCT, :name => 'e', :class => HpgcJobException}
    }

    def struct_fields; FIELDS; end

    def validate
    end

    ::Thrift::Struct.generate_accessors self
  end

  class Start_args
    include ::Thrift::Struct, ::Thrift::Struct_Union
    FLOW = 1

    FIELDS = {
      FLOW => {:type => ::Thrift::Types::STRUCT, :name => 'flow', :class => JobFlow}
    }

    def struct_fields; FIELDS; end

    def validate
    end

    ::Thrift::Struct.generate_accessors self
  end

  class Start_result
    include ::Thrift::Struct, ::Thrift::Struct_Union
    SUCCESS = 0
    E = 1

    FIELDS = {
      SUCCESS => {:type => ::Thrift::Types::I32, :name => 'success'},
      E => {:type => ::Thrift::Types::STRUCT, :name => 'e', :class => HpgcJobException}
    }

    def struct_fields; FIELDS; end

    def validate
    end

    ::Thrift::Struct.generate_accessors self
  end

  class Pause_args
    include ::Thrift::Struct, ::Thrift::Struct_Union
    CLIENT_TICKET = 1

    FIELDS = {
      CLIENT_TICKET => {:type => ::Thrift::Types::I32, :name => 'client_ticket'}
    }

    def struct_fields; FIELDS; end

    def validate
    end

    ::Thrift::Struct.generate_accessors self
  end

  class Pause_result
    include ::Thrift::Struct, ::Thrift::Struct_Union

    FIELDS = {

    }

    def struct_fields; FIELDS; end

    def validate
    end

    ::Thrift::Struct.generate_accessors self
  end

  class Resume_args
    include ::Thrift::Struct, ::Thrift::Struct_Union
    CLIENT_TICKET = 1

    FIELDS = {
      CLIENT_TICKET => {:type => ::Thrift::Types::I32, :name => 'client_ticket'}
    }

    def struct_fields; FIELDS; end

    def validate
    end

    ::Thrift::Struct.generate_accessors self
  end

  class Resume_result
    include ::Thrift::Struct, ::Thrift::Struct_Union

    FIELDS = {

    }

    def struct_fields; FIELDS; end

    def validate
    end

    ::Thrift::Struct.generate_accessors self
  end

  class Cancel_args
    include ::Thrift::Struct, ::Thrift::Struct_Union
    CLIENT_TICKET = 1

    FIELDS = {
      CLIENT_TICKET => {:type => ::Thrift::Types::I32, :name => 'client_ticket'}
    }

    def struct_fields; FIELDS; end

    def validate
    end

    ::Thrift::Struct.generate_accessors self
  end

  class Cancel_result
    include ::Thrift::Struct, ::Thrift::Struct_Union

    FIELDS = {

    }

    def struct_fields; FIELDS; end

    def validate
    end

    ::Thrift::Struct.generate_accessors self
  end

  class Get_status_args
    include ::Thrift::Struct, ::Thrift::Struct_Union
    CLIENT_TICKET = 1

    FIELDS = {
      CLIENT_TICKET => {:type => ::Thrift::Types::I32, :name => 'client_ticket'}
    }

    def struct_fields; FIELDS; end

    def validate
    end

    ::Thrift::Struct.generate_accessors self
  end

  class Get_status_result
    include ::Thrift::Struct, ::Thrift::Struct_Union
    SUCCESS = 0

    FIELDS = {
      SUCCESS => {:type => ::Thrift::Types::STRUCT, :name => 'success', :class => Result}
    }

    def struct_fields; FIELDS; end

    def validate
    end

    ::Thrift::Struct.generate_accessors self
  end

end

