/**
 * Autogenerated by Thrift Compiler (0.7.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */

namespace HPGC.HiGIS.Server
{
  public enum ParallelEnv
  {
    MPI = 1,
    OPENMP = 2,
    CUDA = 3,
    MAPREDUCE = 4,
  }
}
