/**
 * Autogenerated by Thrift Compiler (0.7.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */

namespace HPGC.HiGIS.Server
{
  public enum Status
  {
    FINISHED = 1,
    RUNNING = 2,
    FAILED = 3,
    NOT_EXIST = 4,
    PAUSED = 5,
  }
}
