/**
 * Autogenerated by Thrift Compiler (0.7.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package HPGC.HiGIS.Server;

import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class JobFlowStatus implements org.apache.thrift.TBase<JobFlowStatus, JobFlowStatus._Fields>, java.io.Serializable, Cloneable {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("JobFlowStatus");

  private static final org.apache.thrift.protocol.TField JOB_STATUS_LIST_FIELD_DESC = new org.apache.thrift.protocol.TField("job_status_list", org.apache.thrift.protocol.TType.LIST, (short)1);

  public List<JobStatus> job_status_list; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    JOB_STATUS_LIST((short)1, "job_status_list");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // JOB_STATUS_LIST
          return JOB_STATUS_LIST;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments

  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.JOB_STATUS_LIST, new org.apache.thrift.meta_data.FieldMetaData("job_status_list", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.EnumMetaData(org.apache.thrift.protocol.TType.ENUM, JobStatus.class))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(JobFlowStatus.class, metaDataMap);
  }

  public JobFlowStatus() {
  }

  public JobFlowStatus(
    List<JobStatus> job_status_list)
  {
    this();
    this.job_status_list = job_status_list;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public JobFlowStatus(JobFlowStatus other) {
    if (other.isSetJob_status_list()) {
      List<JobStatus> __this__job_status_list = new ArrayList<JobStatus>();
      for (JobStatus other_element : other.job_status_list) {
        __this__job_status_list.add(other_element);
      }
      this.job_status_list = __this__job_status_list;
    }
  }

  public JobFlowStatus deepCopy() {
    return new JobFlowStatus(this);
  }

  @Override
  public void clear() {
    this.job_status_list = null;
  }

  public int getJob_status_listSize() {
    return (this.job_status_list == null) ? 0 : this.job_status_list.size();
  }

  public java.util.Iterator<JobStatus> getJob_status_listIterator() {
    return (this.job_status_list == null) ? null : this.job_status_list.iterator();
  }

  public void addToJob_status_list(JobStatus elem) {
    if (this.job_status_list == null) {
      this.job_status_list = new ArrayList<JobStatus>();
    }
    this.job_status_list.add(elem);
  }

  public List<JobStatus> getJob_status_list() {
    return this.job_status_list;
  }

  public JobFlowStatus setJob_status_list(List<JobStatus> job_status_list) {
    this.job_status_list = job_status_list;
    return this;
  }

  public void unsetJob_status_list() {
    this.job_status_list = null;
  }

  /** Returns true if field job_status_list is set (has been assigned a value) and false otherwise */
  public boolean isSetJob_status_list() {
    return this.job_status_list != null;
  }

  public void setJob_status_listIsSet(boolean value) {
    if (!value) {
      this.job_status_list = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case JOB_STATUS_LIST:
      if (value == null) {
        unsetJob_status_list();
      } else {
        setJob_status_list((List<JobStatus>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case JOB_STATUS_LIST:
      return getJob_status_list();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case JOB_STATUS_LIST:
      return isSetJob_status_list();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof JobFlowStatus)
      return this.equals((JobFlowStatus)that);
    return false;
  }

  public boolean equals(JobFlowStatus that) {
    if (that == null)
      return false;

    boolean this_present_job_status_list = true && this.isSetJob_status_list();
    boolean that_present_job_status_list = true && that.isSetJob_status_list();
    if (this_present_job_status_list || that_present_job_status_list) {
      if (!(this_present_job_status_list && that_present_job_status_list))
        return false;
      if (!this.job_status_list.equals(that.job_status_list))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public int compareTo(JobFlowStatus other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    JobFlowStatus typedOther = (JobFlowStatus)other;

    lastComparison = Boolean.valueOf(isSetJob_status_list()).compareTo(typedOther.isSetJob_status_list());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetJob_status_list()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.job_status_list, typedOther.job_status_list);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    org.apache.thrift.protocol.TField field;
    iprot.readStructBegin();
    while (true)
    {
      field = iprot.readFieldBegin();
      if (field.type == org.apache.thrift.protocol.TType.STOP) { 
        break;
      }
      switch (field.id) {
        case 1: // JOB_STATUS_LIST
          if (field.type == org.apache.thrift.protocol.TType.LIST) {
            {
              org.apache.thrift.protocol.TList _list0 = iprot.readListBegin();
              this.job_status_list = new ArrayList<JobStatus>(_list0.size);
              for (int _i1 = 0; _i1 < _list0.size; ++_i1)
              {
                JobStatus _elem2; // required
                _elem2 = JobStatus.findByValue(iprot.readI32());
                this.job_status_list.add(_elem2);
              }
              iprot.readListEnd();
            }
          } else { 
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
          }
          break;
        default:
          org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
      }
      iprot.readFieldEnd();
    }
    iprot.readStructEnd();

    // check for required fields of primitive type, which can't be checked in the validate method
    validate();
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    validate();

    oprot.writeStructBegin(STRUCT_DESC);
    if (this.job_status_list != null) {
      oprot.writeFieldBegin(JOB_STATUS_LIST_FIELD_DESC);
      {
        oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.I32, this.job_status_list.size()));
        for (JobStatus _iter3 : this.job_status_list)
        {
          oprot.writeI32(_iter3.getValue());
        }
        oprot.writeListEnd();
      }
      oprot.writeFieldEnd();
    }
    oprot.writeFieldStop();
    oprot.writeStructEnd();
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("JobFlowStatus(");
    boolean first = true;

    sb.append("job_status_list:");
    if (this.job_status_list == null) {
      sb.append("null");
    } else {
      sb.append(this.job_status_list);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

}

