/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package HPGC.HiGIS.Server;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum Status implements org.apache.thrift.TEnum {
  FINISHED(1),
  RUNNING(2),
  FAILED(3),
  NOT_EXIST(4),
  PAUSED(5);

  private final int value;

  private Status(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static Status findByValue(int value) { 
    switch (value) {
      case 1:
        return FINISHED;
      case 2:
        return RUNNING;
      case 3:
        return FAILED;
      case 4:
        return NOT_EXIST;
      case 5:
        return PAUSED;
      default:
        return null;
    }
  }
}
