#!/bin/bash

thrift -r --gen cpp hpgcjob.thrift
thrift -r --gen rb hpgcjob.thrift
thrift -r --gen java hpgcjob.thrift
thrift -r --gen csharp hpgcjob.thrift
thrift -r --gen py hpgcjob.thrift

cp -r gen-cpp/* ../server/lib/
cp -r gen-rb/* ../tests/act/lib/
cp -r gen-rb ../clients/
cp -r gen-cpp ../clients/
cp -r gen-java ../clients/
cp -r gen-csharp ../clients/
cp -r gen-py ../clients/
rm -rf gen-rb
rm -rf gen-cpp
rm -rf gen-java
rm -rf gen-csharp
rm -rf gen-py

