#!/bin/bash

# check if stdin contains specifical message

result="true"
actual=$(cat)

for arg in "$*"
do
	echo $actual | grep -q "$arg"
	if [ ! $? -eq 0 ]; then
		result="false"
		miss="$arg"
		break
	fi
done

# show result
if [ $result == "false" ]; then
	echo "false; not contain $miss"
else
	echo true
fi
