/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "hpgcjob_constants.h"

namespace HPGC { namespace HiGIS { namespace Server {

const hpgcjobConstants g_hpgcjob_constants;

hpgcjobConstants::hpgcjobConstants() {
}

}}} // namespace

